---
- name: Check if jdk is installed  
  register: has_java  
  shell: "which javac"
  changed_when: has_java.rc == 1
  failed_when: false
  notify:
   - install java and maven

- meta: flush_handlers      

- name: fetch maven home
  shell: update-alternatives --display mvn | grep "currently" | sed -n 's/.* \(\/.*\)\/bin\/.*/\1/p'
  register: mavenhomedir
  changed_when: 
    - maven_home | length == 0
  notify:
    - set maven home  
    - source profile
- debug: var=mavenhomedir.stdout_lines

- meta: flush_handlers        

- name: fetch java home
  shell: update-alternatives --display javac | grep "currently" | sed -n 's/.* \(\/.*\)\/bin\/java.*/\1/p'
  register: javahomedir
  changed_when: 
    - java_home | length == 0
  notify:
    - set java home
    - source profile    
- debug: var=javahomedir.stdout_lines

- meta: flush_handlers        


